In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\Lala\Downloads\archive\WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [5]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

## Overall attrition rate:

In [3]:
overall_attrition_rate = df["Attrition"].eq("Yes").mean() * 100

print(f"Overall Attrition Rate: {overall_attrition_rate:.2f}%")

Overall Attrition Rate: 16.12%

## KPI table

In [15]:

total_employees = len(df)
total_attritions = (df['Attrition'] == 'Yes').sum()
attrition_rate = round(total_attritions / total_employees * 100, 2)

churned = df[df['Attrition'] == 'Yes']
retained = df[df['Attrition'] == 'No']


kpi_table = pd.DataFrame({
    'KPI': [
        'Total Employees',
        'Avg MonthlyIncome',
        'Avg YearsAtCompany',
        'Avg JobSatisfaction' ],
    'Churned': [
        len(churned),
        round(churned['MonthlyIncome'].mean(), 2),
        round(churned['YearsAtCompany'].mean(), 2),
        round(churned['JobSatisfaction'].mean(), 2)],
    'Retained': [
        len(retained),
        round(retained['MonthlyIncome'].mean(), 2),
        round(retained['YearsAtCompany'].mean(), 2),
        round(retained['JobSatisfaction'].mean(), 2)]})

In [16]:
kpi_table

                   KPI  Churned  Retained
0      Total Employees   237.00   1233.00
1    Avg MonthlyIncome  4787.09   6832.74
2   Avg YearsAtCompany     5.13      7.37
3  Avg JobSatisfaction     2.47      2.78

In [19]:
kpi_table.style.format({'Churned': '{:.2f}', 'Retained': '{:.2f}'}) \
    .background_gradient(cmap='Reds',axis=1)